Controller.py
Database_connectiondetails.txt
Doberman.py
DobermanDB.py
Plugin.py
ReadoutThread.py

Changes the SQL database backend to use MongoDB instead

Mongo backend

---

ControllerBase.py
Doberman.py
Teledyne.py
iseries.py
smartec_uti.py

Fixes a few problems that occur when you don't test code before committing.

Everything works now

---

Plugin.py
pfeiffer_tpg.py

Converts the Pfeiffer pressure gauge to use LAN rather than USB connection (and patches a few other things to boot)

Pfeiffer patch

---

DobermanDB.py
MKS_MFC.py
Teledyne.py
cryocon_22c.py
isegNHQ.py

Allows you to find out what commands are accepted from the command line, without needing to pull up the wiki or something.

Command help

---

DobermanDB.py
Plugin.py
utils.py

Lets higher-level modules work now. The fix is to move FindPlugin into utils

Fixed circular import issue

---

Doberman.py
DobermanDB.py
DobermanLogging.py
Plugin.py
alarmDistribution.py
test.py

Fully implements logging of messages into the database (also writes to screen).

DB logging

---

DobermanDB.py

Because having only one person able to make the DB calls necessary is not a viable solution.

Change alarm levels from the command line

---

BasePlugin.py
Doberman.py
DobermanDB.py
Plugin.py

Allows the user to specify which runmode to start a controller in. If not specified, defaults to whatever runmode Doberman is currently running in.

Specify runmode when starting controllers

---

DobermanDB.py

Adds extra info like the time since the last measurement and the last values readout

Improves status readout

---

BasePlugin.py
ControllerBase.py
Doberman.py
DobermanDB.py
Teledyne.py
caen_n1470.py
cryocon_22c.py
iseries.py
pfeiffer_tpg.py
smartec_uti.py
utils.py

Fixes #62 for all sensors except the CAEN n1470, which will be fixed later.

Controllers now accept bytes from the sensors, rather than strings

---

Doberman.py
DobermanDB.py
Plugin.py
iseries.py
utils.py

Cleans up a couple of things:
- Removed some unnecessary things from the iseries, and fixed a problem with the `isItMe` routine.
- Starting plugins in the default runmode is now only possible through doberman (ie, if doberman is managing that plugin).
- Fixed some issues with the ttyUSB refresh routine.
- Expanded sleep mode: 
- Checks for the 'wake' command once every heartbeat loop and ignores everything else. It refuses to accept any other commands while this is active.
- You can't put the system to sleep while there are managed plugins.

Take a few rough edges off

---

caen_n1470.py
isegNHQ.py
labjack.py

This updates the GeMSE plugins to:
- have the isegNHQ accept bytes rather than decoded strings, to bring it line with other changes made (mainly for the sake of the Teledyne)
- handle a few minor edge cases in the labjack code

Some patches for the GeMSE plugins

---

ControllerBase.py
DobermanDB.py
sysmon.py

This PR adds a system monitor plugin to ensure the host machine is healthy. To facilitate other software-based plugins, a SoftwarePlugin base class is added, with a member function that handles system calls.
Additionally, the way the system adds new controllers is slightly tweaked. The specified config file is required to be JSON-encoded, and a few extra keys are added if not present.

System monitor

---

cryocon_26.py

As we already have a base cryocon class, a new model is a trivial amount of work.

Add support for cryocon_26

---

DobermanDB.py
Plugin.py
utils.py

Prepends the name of the experiment ('gemse', 'xebra', etc) onto the database name for all calls to allow one server to host databases for multiple instances of Doberman

Adds experiment name

---

BasePlugin.py
BlindPlugin.py
DobermanDB.py
ExampleSensor.py
PID.py
Plugin.py
SensorBase.py
__init__.py

I thought I had made these changes already, but apparently some of them slipped through

Too many branches

---

BlindPlugin.py
Plugin.py
SensorBase.py
utils.py

Fixes #82. Allows serial devices to connect via either COM or USB. COM is harder to dynamically work with but doesn't have the failure problems of the COM-USB adapters.

Adding options for COM port connections

---

BasePlugin.py
Plugin.py
SensorBase.py
caen_n1470.py
iseries.py
labjack.py
smartec_uti.py
utils.py

Fixes some query problems from the tty refreshing routine, and catches some problems that showed up during testing.

Fixed tty_refresh routine

---

labjack.py

This patch overhauls the labjack code to a) work better with v4.x and b) make the system more easily extendable. AddToSchedule does not guarantee threadsafe hardware access, so that's been replaced with something better.

Labjack patch

---

DobermanDB.py
isegNHQ.py

The iseg somehow got partially forgotten during the 4.0 update campaign. This fixes that.

Patch for iseg

---

DobermanDB.py
MKS_MFC.py
isegNHQ.py
labjack.py

Not sure why the merge is happening in the direction it is, somehow branches got mixed up

A few patches for GeMSE

---

DobermanDB.py
MKS_MFC.py
isegNHQ.py
labjack.py

* Initial code for levelmeter
* Caught a typo
* Redoes labjack for v4
* Removed unused import
* Patch for iseg (#94)
* Patch for iseg
* Fixed a few other problems with the iseg
* Added proper ramp feature
* Final updates for iseg
* Forgot an rstrip
* Displays log messages after submitting a command
* Bypasses print statements for non-CLI users
* Wrong regex group
* Some typos on GeMSE codes
* Another typo

A few patches for GeMSE (#100)

---

isegNHQ.py

Fixed typo preventing ramping

---

Doberman/Reading.py

Does a bit of cleanup in the Reading class - some functions were doing too many things without clear structure. Also, there was a bug where a MultiReading would only push to Kafka and not Influx, which is now fixed.

Cleanup, fix bug in MultiReading

---

Doberman/BaseSensor.py
Doberman/Database.py
Doberman/SensorMonitor.py

Simplifies how commands going to sensor hardware are imagined. A driver is still responsible for processing input but the templates are stored in the database. Also tweaks the format in the database to support an indexed query.

Reimagined command formatting

---

Doberman/AlarmMonitor.py
Doberman/Reading.py

Some tweaks to alarm messages.
- Msgs show experiment name
- Time zones are considered
- Only one log info for no more shifters instead of every minute. 
- Simple reading alarm shows Description instead of sensor name, but this will go away anyway

Alarm messages

---

Doberman/Database.py
Doberman/Reading.py

Stores the high and low alarm values (if they exist) with the entry going to influx

Alarms in influx

---

Doberman/Database.py
Doberman/Pipeline.py

Mainly tweaks now that we've got influx2 running and loaded. Still need to make sure that the timestamp in the csv data has the correct number of zeroes; initial testing puts it at 6 too many.

Some influx things

---

Doberman/BaseSensor.py
tests/TestSensor.py
tests/TestSensorServer.py

Now without 380 unnecessary commits following some rebasing/merging shenanigans.

Lab simulator

---

.gitignore
Doberman/Reading.py
Doberman/SensorMonitor.py

By "improved" I mean that it should now work more or less as intended. The db will need a minor update before deployment.

Improved MultiReadings

---

Doberman/BaseSensor.py
Doberman/Reading.py

It's more efficient to push data between threads rather than pulling.

Threads push rather than pull

---

Doberman/Reading.py

If you want to do some polynomial transformation to a value before it gets pushed into the database (for instance changing its units), this can be done by specifying a `value_xform` field in the reading document, with little-endian form `[a0, a1, a2...]`. The final value is calculated via `sum(ai*v**i)`. The default value is `[0, 1]` which results in no change.

Adds polynomial transformation option

---

Doberman/ControlNode.py
Doberman/Node.py
Doberman/Pipeline.py

This node requires two EvalNodes upstream to determine `low_condition` and `high_condition`, but should be generalized enough that we can don't need something fancier and should do basically everything we want.

Adds a generalized control node

---

Doberman/Pipeline.py
Doberman/PipelineMonitor.py
Doberman/hypervisor.py
scripts/start_process.sh

I found and fixed a bunch relating to pipelines and the hypervisor starting them.

Tweaks and typos

---

Doberman/BaseDevice.py
Doberman/DeviceMonitor.py
Doberman/Sensor.py

Rather than having the Device own the info, the Sensor can own this. This makes queuing commands slightly cleaner.

Moves info about sensor readout commands into Sensor class

---

Doberman/Node.py
Doberman/Sensor.py

Fixes #151. Also fixes a typo in the InfluxSinkNode

Multisensors no longer require the same topic

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/Database.py
Doberman/DeviceMonitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/Sensor.py
Doberman/hypervisor.py
Doberman/utils.py

I pushed as you, but whatever. These are the fixes from apollo plus an update to the AlarmMonitor, which should be working as intended now.

Alarm update

---

Doberman/AlarmMonitor.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/DeviceMonitor.py
Doberman/Monitor.py
Doberman/hypervisor.py

I don't know why this includes the thread-changes, but the relevant changes are in the ALarmMonitor

Check shifters

---

Doberman/AlarmMonitor.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/Database.py
Doberman/DeviceMonitor.py
Doberman/Node.py
Doberman/Pipeline.py
scripts/start_process.sh
scripts/system_monitor.py

Local changes

---

Doberman/Pipeline.py

Hopefully fixes #170, but I've already said that before for the drift problem.

Maybe fix for #170

---

Doberman/AlarmMonitor.py

fix in make phonecall

---

Doberman/Pipeline.py

Disjoint pipelines hotfix

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/ControlNode.py
Doberman/Database.py
Doberman/DeviceMonitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py
Doberman/Sensor.py
Doberman/__init__.py
Doberman/hypervisor.py
Doberman/utils.py
scripts/make_test_pl.py

Adds support for a new SourceNode that receives data directly from Sensors, rather than having to go through the database as an intermediate step. Envisioned for Control and Convert pipelines. Sensors send their values both to Influx and also to the Control and Convert pipeline monitors. This inter-communication is not done through the hypervisor to reduce bottlenecking (note - do some benchmarking to see how high the rate can go).
Also adds a variety of other things related to hypervising, and a few optimizations to reduce the number of database queries.
Also fixes #178, fixes #177, fixes #170, fixes #166

Synchronous pipelines

---

Doberman/AlarmMonitor.py
Doberman/BaseMonitor.py
Doberman/Database.py
Doberman/DeviceMonitor.py
Doberman/Monitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py
Doberman/Sensor.py
Doberman/hypervisor.py
Doberman/utils.py

This fixes a lot of small things so that the last few pull requests are working properly

Pre release fixes

---

Doberman/BaseDevice.py

Continue asking for data from LAN sensors until they send the end of line character, rather than waiting an arbitrary 1 second (or more). Also tidy up a bit and avoid functions just to set / override (constant) member variables. Fixes #83 (for ethernet sensors). We don't have any serial sensors any more, maybe we can close that issue?

Wait for LAN data rather than sleeping arbitrarily (#206)

---

Doberman/AlarmNode.py

show sensor description in not responding alarm 

---

Doberman/AlarmNode.py
Doberman/Node.py

Fix Alarm pipelines don't change level when running

---

Doberman/Node.py
Doberman/Pipeline.py

Fix sync pipelines

---

Doberman/AlarmMonitor.py

Adds links to email to
- show sensor detail of sensors involed in the pipeline
- silence pipeline for longer than automatic silence period.

Add additional info to email alarms

---

Doberman/AlarmNode.py
Doberman/ControlNode.py
Doberman/Database.py
Doberman/Node.py
Doberman/Pipeline.py

This update enables the use of a flashing light that gets enabled when any alarms or alarms from a certain list are triggered. How it works:
- Added field `alarm_is_triggered : true/false` to each sensor
- Alarm nodes set this field to `true` when alarm condition is met and `false` once the condition isn't met anymore or the pipeline is stopped (this is independent of the pipeline being silenced or not)
- Added `TriggeredAlarmsNode` which gives an output 1 if any of the alarms in its config `sensors_to_check` is triggered (set to "any" if all sensors shall be checked). Otherwise outputs 0.
- A reasonable pipeline would therefore start with a `SensorSourceNode` with one of the X_SYNC signals as `input_var` to get a periodic processing of the pipeline. Follow this by a `TriggeredAlarmsNode` …

Flashing light support
