AG-Schumann/Doberman

DobermanDB.py

Adds a row `_id` to every table creation call. The existing config and contact tables have already been upgraded in the database (to remove the duplicate entries). Fixes #6.

Added primary keys to table creation

---

ControllerBase.py
Doberman.py
DobermanDB.py
DobermanLogging.py
ExampleController.py
LICENSE.md
Longwatch.py
MKS_MFC.py
Plugin.py
Teledyne.py
caen_n1470.py
cryocon_22c.py
heartbeat.py
isegNHQ.py
iseries.py
pfeiffer_tpg.py
settings/Database_connectiondetails.txt
smartec_uti.py
utils.py

Separates the running of plugins from Doberman. Doberman now starts plugins in standalone mode and lets them do their thing. Issues the 'all stop' command when it returns.
Added an 'all' option to commands, which distributes the given command to all currently running controllers. Adds a 'online' field to each controller doc which serves as its lockfile (also added a `--force` command-line option that ignores this - use at your own risk). Replaces the lockfile functionality with a field in the `settings.defaults` collection.
Changed `stilltesting` in the logging module to `False`, so log messages are now stored in the database rather than put to screen (except for `debug` level messages, which are not stored). Also added a `Longwatch` script that pulls log and prints log messages, so logs …

Independence

---

ControllerBase.py
Doberman.py
iseries.py
requirements.txt

Increases the waiting time between asking a serial device for a measurement and reading the value out. Also gives the iseries a second chance to return data if it doesn't the first time (fixing #27).

Fix for crashing iseries

---

DobermanDB.py

Fixes #44. Listing runmodes is possible via the `--help` command line option in Plugin.py, but there's no reason why it shouldn't be under the main command help routine.

Added runmodes to help command

---

ControllerBase.py

If the 'baud' field exists in the config document, the device will use the specified baud rate instead of the default 9600. Might help with Teledyne issues. Fixes #56.

Adds configurable baud rate

---

Doberman.py
Plugin.py

If the database thinks that the Doberman executable is running when it starts, it then checks to see how recently the last heartbeat was. If this is too far in the past, it ignores the "online" field and starts anyway. This should allow the system to recover if it is not stopped gracefully.

Restarts after crashes

---

BasePlugin.py
ControllerBase.py
Teledyne.py

The Teledyne sometimes returns bytes that `bytes.decode()` can't handle. This causes the code to throw unexpected exceptions (it starts with a `UnicodeDecodeException` in `ControllerBase.py`, but is somehow converted into a `TypeError` about string formatting when it reaches the end) which crashes the plugin. This PR improves the way the code handles un-decodable strings by catching the exception and sending the un-decoded string upstream and assuming the plugin code will deal with it.

Fixes unicode decode error

---

Doberman.py
DobermanDB.py
Plugin.py
utils.py

Fixes #48 by adding heartbeats into the controlling executable for every plugin. If a plugin doesn't report in when it should, Doberman tries to restart it. If this is unsuccessful, an alarm is issued.
To handle this, Doberman keeps track of which plugins it starts and checks the heartbeat of only these.

Everything now heartbeats

---

Plugin.py
utils.py

Fixes #59 by having plugins un-manage themselves only when killed with SIGINT (2), rather than SIGKILL (15). This way, when Doberman restarts, there will still be plugins in the managed list that it will restart sooner or later

Plugin management depends on kill signal

---

BasePlugin.py
ControllerBase.py
ExampleController.py
MKS_MFC.py
Teledyne.py
caen_n1470.py
cryocon_22c.py
isegNHQ.py
iseries.py
labjack.py
pfeiffer_tpg.py
smartec_uti.py
utils.py

The old method of endless calls of `super().__init__` in controller drivers is a terrible solution, as there wasn't a consistent order between this call and controller-specific stuff. This PR solves this by adding `SetupBeforeOpening` and `SetupAfterOpening` prototypes for controllers to reinstance, which is code to be executed before or after opening the connection to the device. `SetupBeforeOpening` is called after values from the database are loaded, so this function will have access to that information.

Controller init

---

BasePlugin.py
DobermanDB.py
ExampleSensor.py
MKS_MFC.py
Plugin.py
SensorBase.py
Teledyne.py
caen_n1470.py
cryocon_22c.py
cryocon_26.py
isegNHQ.py
iseries.py
labjack.py
pfeiffer_tpg.py
smartec_uti.py
sonar.py
sysmon.py
utils.py

Rather than remembering which reading corresponds to which index, it's much better to have them as dicts which can be referenced by name and not index.
Additionally, the data storage format is changed. A plugin will buffer all its data for `utils.buffer_timer` seconds, then assemble those into a single document to be inserted into the database (with objectid as the timestamp). Duplicate values from one reading are ignored; only the most recent is taken. This means that a reading with a readout interval faster than the buffer timer will not record data more frequently, and that all measurements will have an uncertainty on the actual measurement time of half the buffer timer.
Readings are now stored as individual documents in a separate collection to simplify the threadsafe-ness of access.

No more arrays

---

Doberman/Node.py
Doberman/PipelineMonitor.py

The time between different values can vary by up to 8ms, so 1ms of drift doesn't prevent hitting the duplicate-value problem. This PR adds a tweak so if we do get a duplicate, we try again once, because pinging the db takes ~30ms which is longer than any reasonable variation.

Drift not quite enough

---

Doberman/BaseMonitor.py
Doberman/Database.py

Rather than have listener ports be assigned in perpetuity, we should return them to the pool when that process shuts down. This ensures we don't store leases for things that will never be used again.

Release listener ports on shutdown

---

Doberman/Sensor.py

This causes many problems and solves none, so let's not write alarm thresholds to influx.

no writing of alarm_thresholds to influx

---

Doberman/AlarmMonitor.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/DeviceMonitor.py
Doberman/Monitor.py
Doberman/hypervisor.py

On rare occasions we've seen threads disappear silently from Monitors. This is obviously bad for a many reasons. This PR adds two extra layers of protection against this: some threads can be designated as do-not-stop threads, where any call to `stop_thread` will fail with a critical message. Second, objects registered as functions (rather than threads) can get restarted if they do happen to fail.
Also, the ownership of a device's readout scheduling thread has been moved up to the DeviceMonitor class so it can get `registered` and be part of the improved thread monitoring.

Improved thread overwatching

---

Doberman/AlarmNode.py
Doberman/Node.py

The `DeviceRespondingAlarm` couldn't handle the recursion in the `InfluxSourceNode`. This PR removes the recursion and resulting error message.

Fix for inheritance-based bug

---

Doberman/AlarmNode.py
Doberman/Pipeline.py

Separates nodes into disjoint sets. During processing, if one node throws an error, other sub-pipelines can still operate as usual. Some extra handling is added to allow AlarmNodes to bypass the "silence" requirement if they are of a higher-level than the silencing, so if a pipeline is silenced by a level 1 alarm, but another alarm at level 2 shows up, the level 2 alarm gets logged like the pipeline wasn't silenced.

Improved support for disjoint pipelines

---

Doberman/ControlNode.py
Doberman/Node.py
Doberman/Pipeline.py

If an error happens during a Pipeline cycle, we should have the option for ControlNodes to do some "default" action, eg closing a valve.

Adds default action for Nodes

---

Doberman/Pipeline.py

As well as putting configuration options per node under `node_config.node` you can put them under `pipeline_config` to be shared across the pipeline. Solves #164

Allow general pipeline configuation

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/BaseMonitor.py
Doberman/ControlNode.py
Doberman/Database.py
Doberman/Monitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py
Doberman/hypervisor.py
scripts/start_process.sh

A number of organizational changes meant to simplify operation. Including:
- The unification of the alarm monitor and the alarm pipeline monitor
- Pipelines must come in one of three flavors: alarm, control, and convert. A dedicated monitor will handle all pipelines of a given flavor, gone are control pipelines running separately
- The hypervisor will start all three Pipeline monitors when it begins; the assumption is that the hypervisor is the first thing to start, and its job is to bring the rest of the system up.
- The `GeneralValveControl` node has been renamed to `GeneralDigitalControl` to handle two-state outputs, and a corresponding `GeneralAnalogControl` will handle floating-point outputs.
- Scaffolding for a control node to affect pipelines. Not yet functional.

Organizational changes

---

Doberman/AlarmMonitor.py

Directly use the websms API instead of email to SMS conversion. Gives us more control. Importantly we can set the message sender number. This is important so people can add it to their contacts / bypass do not disturb / set a loud ringtone for that contact etc.
There is probably a clever way to combine send_sms and send_phonecall, and allow for flexibility for future services. In the end they are all post requests that take some set of parameters stored in the database and send the message with a specific key, getting back a response code. I started to go in this direction with the generic "postparameters" database entry, but more work is needed (variable message formatting, response code interpretation) and there are more pressing things

Directly use WebSMS API, send ID

---

Doberman/AlarmNode.py
Doberman/ControlNode.py
Doberman/Node.py

Mainly a bit of cleanup:
- The names of all nodes now ends in 'Node'. Previously this was not the case, which made some things ambiguous.
- DigitalControlNodes can now be set to run on a single input, rather than having `condition_a` and `condition_b`. This input will be written directly to the designated target.
- PipelineControlNode now actually implemented
- Can no longer even accidentally send the `length` config option to a MergeNode.

Tweaks and cleanup

---

Doberman/BaseDevice.py

Puts them into a `params` dict, rather than setting them as attributes.

Tweak to how params are stored

---

Doberman/BaseMonitor.py
Doberman/Pipeline.py

Give less cryptic error message (at least for a typical user) when a node type name is misspelt

Improve pipeline build logging

---

Doberman/PipelineMonitor.py

By checking if the pipeline is already active and activating it early on in the process, this might avoid getting a same pipeline activated multiple times
Could this be added to pipeline improvements or won't it work ?
I am not sure how to check because I don't know how to reproduce the error
I am not sure either if the "return -1" in line 37 would be the correct way to deal with an already active pipeline
Would solve #196 if it works

Avoiding a pipeline to be active twice

---

Doberman/AlarmNode.py
Doberman/ControlNode.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py

Various small improvements to pipeline functioning (gets the PipelineControlNode working) and error reporting
- Refactors the sensor config loading for alarm nodes to be a little less obscure (and less of the slightly nasty isinstance checks)
- Alarms for the IntegerAlarmNode are now enumerated in the sensor under `alarm_values` rather than `alarm_thresholds`: cannot store different types of data under the same key in MongoDB
- Various logging messages now include the node name
- PipelineControlNode is now a subclass of Node, not ControlNode. Why? Because it doesn't make use of any of the ControlNode code, and indeed that gets in the way. They are fundamentally very different - ControlNode is designed for physical outputs.
- Rewrote the PipelineControlNode logic to allow (a) arbitrarily …

Pipeline improvements

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py

* Instead of computing a slightly arbitrary max reading delay from the bad recurrence, use a fixed value from the database. Why? Because this number represents our trust in readings arriving in a timely fashion, rather than anything to do with how often the sensor must be bad before issuing an alarm
* Changed the way we check whether alarms were issued properly to use exceptions rather than return values (probably slightly more robust and certainly easier to keep track of - all exceptions are now caught only by the log_alarm function of AlarmNode before silencing the pipeline)
* When the user presses silence on the website, the level is -1 (meaning universal for all pipelines) instead of 0 (previous default, only silencing level 0 alarms)
* The start command doesn't reactivate silenced …

Alarm and pipeline tweaks

---

Doberman/BaseDevice.py

Continue asking for data from LAN sensors until they send the end of line character, rather than waiting an arbitrary 1 second (or more). Also tidy up a bit and avoid functions just to set / override (constant) member variables. Fixes #83 (for ethernet sensors). We don't have any serial sensors any more, maybe we can close that issue?

Wait for LAN data rather than sleeping arbitrarily

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/BaseDevice.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py

Allows sending a test alarm by passing the 'testalarm [LEVEL]' command to the alarm pipeline monitor.
Also fixes a bug in the alarm sending whereby if one communication mechanism doesn't work (e.g. email fails) the others may not be tried, depending one what order the connection details are stored in the database. Now all are tried and an exception is nevertheless raised if one fails by log_alarm in AlarmMonitor.py.
In AlarmNode.log_alarm the exception is caught and an additional database parameter (silence_duration_cant_send) determines how long the pipeline should be silenced (to avoid sending a new alarm for every subsequent reading if there is still a problem.
For now, for pancake, this is set to 60 seconds.

Enable test alarms and more reliable alarm sending

---

Doberman/BaseDevice.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py

Currently, silencing works as follows:
- Set status to `silent`
- Put command into queue that activates pipeline again at a certain time in the future
The problem with this is, that you cannot easily prolong the silence period of a pipeline (Basically, you'd have to remove the initial reactivation command from the command queue which is a bit complicated). So I suggest the following:
- allowed values for a pipeline's status: 'active', 'inactive' (no more silent status)
- Wether or not a pipeline is silent is determined via the `silent_until` field in its DB doc. 
- if `silent_until > current time or  == -1 (silent forever)` the pipeline is silent else it's not
This should already include all the changes, but requires testing.
This change also needs a small tweak in doberview.

Silence rework

---

Doberman/Node.py
Doberman/Pipeline.py
Doberman/hypervisor.py
scripts/start_process.sh

Improvements to the shutdown sequence of the hypervisor.
Keyboard interrupt the hypervisor will now close all three pipeline monitors and all managed devices. 
Also seems to fix #192. At least, I don't observe this issue anymore.

Shutdown sequence

---

Doberman/ControlNode.py

Sometimes having just condition_a and condition_b hardcoded is not enough (if you want multiple control nodes in one pipeline). Probably better to make them a config option.
Note this is not backwards compatible for non-single-input control nodes so their config would need updating

Custom control node inputs

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/hypervisor.py

I implemented the `check_remote_heartbeat` part. 
- New node type`CheckRemoteHeartbeatNode` can be used in pipelines. Most likely you want one of the SYNC signals to be the input to give the period (i.e. execute the check every 60 seconds). Like this, silencing, reactivating, etc. of remote heartbeat alarms becomes trivial. 
- depending on `max_delay_sms` and `max_delay_phone` it then send SMS and phone calls to the shifters numbers in the remote_hb document. Like this, you reach the shifters of the remote experiment and don't have to rely on someone of the local experiment, which might not have shifters at this point or whatever.
Also addresses one of the comments of the experimental -> master PR and changes again a bit the shutdown sequence of the hypervisor since it could happen before …

Remote hb pipeline

---

Doberman/Pipeline.py
Doberman/PipelineMonitor.py

Maybe this was the cause for #225 - hard to tell from the given information. Was intended as a feature, but I guess it's better when all the same pipelines start up again after someone shuts down the PipelineMonitor.

Don't deactivate pipeline when shutting down PipelineMonitor

---

Doberman/ControlNode.py
scripts/make_test_pl.py
setup.py

There was a small problem with the test_pipeline that creates itself on start-up. Like this, it now uses the generic PipelineControlNode instead of some hardcoded stuff.

Fix test pipeline

---

Doberman/BaseMonitor.py
Doberman/Monitor.py

This causes a very annoying bug, where you 'activate' a device e.g. via the website and it doesn't start properly (i.e. you run into the Exception in line 65/66 of Monitor.py), it makes it impossible to deactivate it again, unless you do it via MongoDB.
With this fix the device just won't activate and together with [unmanage_inactive](https://github.com/AG-Schumann/doberview2/pull/76), you can then just unmanage the device once you see it failed to start so it doesn't try to restart it over and over again.

Do not set monitor active on failure

---

Doberman/AlarmNode.py

- Makes IntegerAlarmNode a BufferNode so it doesn't automatically trigger after one value but after the recurrence defined in sensor settings (i.e. just like a simple alarm). Solves #235 .
- Adds `TimeSinceAlarmNode` that triggers once a sensor has been measuring the `alarm_value` for longer than the `max_duration`. It only really makes sense for integer sensors (e.g. 'this valve has been open for too long!'), but I don't see a use-case for a 'time since out of threshold'-alarm. Or put in another way, this would be the same as a SimpleAlarm with the right recurrence setting, or am missing something? Solves #236

Alarm node updates

---

Doberman/AlarmMonitor.py
Doberman/AlarmNode.py
Doberman/BaseDevice.py
Doberman/BaseMonitor.py
Doberman/ControlNode.py
Doberman/Database.py
Doberman/DeviceMonitor.py
Doberman/Monitor.py
Doberman/Node.py
Doberman/Pipeline.py
Doberman/PipelineMonitor.py
Doberman/Sensor.py
Doberman/hypervisor.py
Doberman/utils.py
scripts/start_process.sh

Logging is quite inconsistent and I personally never find what I want at the place I expect it. Some rules that make sense to me:
- Avoid repeating DEBUG-level messages. They are great during development but at the current state they clog the debug logs and are not used anymore.
- Use WARNING for things that are expected but should be in the website logs. Like 'alarm for sensor XXX', 'sending SMS to ...'
- Use WARNING also for things that are somewhat unexpected but don't hinder Doberman's operation too much. E.g. 'didn't get a value from device XXX' which could be a one time thing or more regular -> Good to see these on the website
- Use ERROR for (most) caught exceptions. Here something just did not work as it should. A device/pipeline didn't get started, an alarm message could not be …

Better logging

---

Doberman/AlarmNode.py

The device responding nodes are not working. When they [log the alarm](https://github.com/AG-Schumann/Doberman/blob/master/Doberman/AlarmNode.py#L54),` config['alarm_level']` throws a `KeyError` . This need to be fixed ASAP.

Fix KeyError in DeviceRespondingNodes

---

Doberman/AlarmNode.py
Doberman/BaseMonitor.py

This bug became only apparent once we fixed the hashing system, I guess.
**Intended function:** 
- if all values in the AlarmNode's buffer are bad -> Send alarm
- if any value is okay (1 or more) -> do nothing
- if all values in the buffer are okay -> Reset the escalation level. 
The way it was coded, the last condition was never reached (because `pass` ends the if-elif-else statement)
Also, I think the escalation happened one message too late. Depends a bit on the wording. 
Also there is one more map()-function bug fixed in the Monitor shutdown sequence.

Make reset_alarm work
